_wandb:
    value:
        cli_version: 0.19.8
        m:
            - "1": rollout/ep_rew_mean
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": global_step
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": time/fps
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": rollout/ep_len_mean
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 2
                - 3
                - 55
            "2":
                - 1
                - 2
                - 3
                - 55
            "3":
                - 2
                - 7
                - 13
                - 23
                - 35
                - 55
            "4": 3.10.16
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
